### ISSUE TITLE
Sector loading problem

### ISSUE THREAD

**Issue by Jimx-** [boskee/Minecraft#75]
@Nebual I notice that when I start game and connect to a server, the sector_packet stays 0 for about 20~30 seconds and after such a long time, it increases rapidly to 1000+ and the world is loaded in few seconds. I've tried it on several computers but the same problem happened. change_sectors is called as soon as the game connect to the server and begin to request sectors. So is this a server-side problem or something else？

**Comment by r58Playz** [comment]
Personally for me, the world starts loading as soon as the main menu disappears, and it's super laggy until the world fully loads. Then it's laggy when I press W, S, A, D, or space. When I try to break a block, it does nothing. If I try to break the same block again, the server gives me a `KeyError`.

It's weird.

**Comment by ronmurphy** [comment]
you do realize that this project has not been updated or touched in YEARS, and as fast as the linux world progresses, updating the whole project to current standard to take advantage of updated apps and such is a huge undertaking... 

Feel free to start debugging.  just keep in mind, most of these files are 5-6 years old, and that python and such has changed.   also keep in mind, this uses python 2, not 3.

**Comment by Nebual** [comment]
I may have some fixes for the originally reported issue, which is that the world seems to take a long time to initially load, opening a PR shortly.

There's a separate issue that running "Singleplayer" (which launches the server in the same process, in a separate thread) is considerably laggier (FPS wise) than launching `python server.py` separately and connecting to it. It feels as if the GIL isn't being properly released back to the GUI thread while the server is generating/loading a chunk. I may investigate subprocesses for that...

#89 is a separate issue regarding Pyglet updating their API over the years...
