### ISSUE TITLE
Sky artwork is stolen

### ISSUE THREAD

**Issue by Natureshadow** [boskee/Minecraft#84]
The sly artwork is in resources/ is stolen from CGSkies, where it is proprietary and sold for USD $30.

It has illegaly been relicensed under the MIT license, at least according to the information stated in this repository.

Please remove it, maybe even asking GitHub to rewrite the history of the repository to get it removed from all commits.

**Comment by ronmurphy** [comment]
can you specify what art is stolen?  what is the file name?  I can change it out for something else.

**Comment by bitcraft** [comment]
Image source: http://www.cgskies.com/sky.php?sky=339

The web site says "Sample images are for non-commercial, educational or testing purposes only. For commercial projects you must purchase the sky."

**Comment by Nebual** [comment]
I believe this project easily falls under the category of developed for noncommercial educational/testing purposes, and we're only using the sample images. Should you wish to send us a formal take down request, feel free to email us or link a PDF of something more official than a Github Issue.

**Comment by Natureshadow** [comment]
It is not important what I believe.

You expressly attached a copy of the MIT license for the project, including the image, and you do not have the rights to share it under this license because it clearly states that commercial use is allowed.

I cannot seem to find words for such behaviour and ignorance.

If you do not know what a license is and/or do not care and/or want to be an ass and give a damn on other people's rights, then please do not publish code or other works that even remotely interfere with others.

Thanks!

**Comment by Nebual** [comment]
I'm a programmer, not an international copyright enthusiast. I believe the original license (which is technically just copied from Fogleman's original repo years ago) was only meant to cover the code and documentation, but as we happen to have a Used Media Licenses file I've added a reference for the sky image to it, thus removing it from the implied MIT license. 

Thanks for your contribution to the project!

**Comment by Natureshadow** [comment]
OK, that sounds reasonable. It is not perfect because from a free software POV, it still renders the project unusable, but this can be fixed by any user by replacing the artwork on forking.

That said, thanks for keeping the FOSS community's relations to others in good shape by indicating interest for their rights!
